services:
  grece:
    build: . # Esto le dice a Docker que use tu Dockerfile para construir la imagen
    container_name: grece
    restart: unless-stopped
    # Eliminamos el volumen de ./www porque el Dockerfile ya copia los archivos a /usr/share/nginx/html
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8n_default"
      - "traefik.http.routers.grece.rule=Host(`grece.bleepy.com.ar`) || Host(`grece.xyz`) || Host(`www.grece.xyz`)"
      - "traefik.http.routers.grece.entrypoints=websecure"
      - "traefik.http.routers.grece.tls=true"
      - "traefik.http.routers.grece.tls.certresolver=mytlschallenge"
      - "traefik.http.services.grece.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
    name: n8n_default
